# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_teacher', to='polls.Profile'),
        ),
    ]
