# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171222_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='workload',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='工作量'),
        ),
    ]
