# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_classschedule_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='workload',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='工作量'),
        ),
        migrations.AddField(
            model_name='guidepaper',
            name='workload',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='工作量'),
        ),
        migrations.AddField(
            model_name='teachachievement',
            name='workload',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='工作量'),
        ),
        migrations.AddField(
            model_name='teachobject',
            name='workload',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='工作量'),
        ),
    ]
