# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171222_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='place',
            field=models.CharField(blank=True, default='未填写', max_length=30, null=True, verbose_name='地点'),
        ),
    ]
