# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171223_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='提高一班', max_length=20, unique=True, verbose_name='班名'),
        ),
    ]
