# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171224_1338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set([('year', 'term', 'teacher_id', 'class_id', 'course_id')]),
        ),
    ]
