# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171224_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='分子生物学', max_length=20, unique=True, verbose_name='课程名'),
        ),
    ]
