# -*- coding:utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^index/login/$', views.index_login, name='index_login'),
    url(r'^index/logout/$', views.index_logout, name='index_logout'),
    url(r'^index/change_password/$', views.index_change_password, name='index_change_password'),
    url(r'^index/register/(?P<type>[0-9]+)/$', views.index_regisiter, name='index_register'),
    url(r'^index/teacher/$', views.index_teacher, name='index_teacher'),
    url(r'^index/alert/teacher/info/(?P<teacher_id>[0-9]+)$', views.index_alert_teacher_info,
        name='index_alert_teacher_info'),
    url(r'^index/alert/reject/OB/reason/(?P<items_id>[0-9]+)$', views.index_alert_OB_reject_reason,
        name='index_alert_OB_reject_reason'),
    url(r'^index/alert/reject/CM/reason/(?P<items_id>[0-9]+)$', views.index_alert_CM_reject_reason,
        name='index_alert_CM_reject_reason'),
    url(r'^index/alert/reject/PA/reason/(?P<items_id>[0-9]+)$', views.index_alert_PA_reject_reason,
        name='index_alert_PA_reject_reason'),
    url(r'^index/alert/reject/TA/reason/(?P<items_id>[0-9]+)$', views.index_alert_TA_reject_reason,
        name='index_alert_TA_reject_reason'),
    url(r'^index/alert/reject/class/reason/(?P<items_id>[0-9]+)$', views.index_alert_class_reject_reason,
        name='index_alert_class_reject_reason'),
    url(r'^index/alert/class_schedule/course/(?P<course_id>[0-9]+)$', views.index_alert_course_info,
        name='index_alert_course_info'),
    url(r'^index/alert/class_schedule/class/(?P<class_id>[0-9]+)$', views.index_alert_class_info,
        name='index_alert_class_info'),

    #注册模板url
    url(r'^index/teacher/workload_count/$', views.workload_count, name='workload_count'),
    url(r'^index/teacher/user_info/$', views.index_teacher_user_info, name='index_teacher_user_info'),
    url(r'^index/teacher/add/class_schedule/$', views.index_teacher_new_class_schedule, name='index_teacher_new_class_schedule'),
    url(r'^index/teacher/edit/class_schedule/(?P<class_schedule_id>[0-9]+)/$',
        views.index_teacher_edit_class_schedule, name='index_teacher_edit_class_schedule'),
    url(r'^index/teacher/theory_class/(?P<type>[0-9]+)/$', views.index_teacher_class_theory, name='index_teacher_class_theory'),
    url(r'^index/teacher/theory_class/pass/(?P<type>[0-9]+)/$', views.index_teacher_class_pass, name='index_teacher_class_pass'),
    url(r'^index/teacher/theory_class/select/(?P<tp>[0-9]+)/$', views.index_teacher_class_select,
        name='index_teacher_class_select'),
    url(r'^index/teacher/theory_class/select/(?P<record_id>[0-9]+)/$', views.index_teacher_delete_class_schedule,
        name='index_teacher_delete_class_schedule'),
    url(r'^index/teacher/theory_class/reject_reason/$', views.index_teacher_class_reject_reason,
        name='index_teacher_class_reject_reason'),

    url(r'^index/teacher/teaching_achievement/$',views.index_teacher_teaching_achievement,name='index_teacher_teaching_achievement'),
    url(r'^index/teacher/teaching_achievement/add_jiao_gai_xiang_mu/$',views.index_teacher_new_jiao_gai_xiang_mu,name='index_teacheer_achievement_new_jiao_gai_xiang_mu'),
    url(r'^index/teaher/teaching_achievement/select/$',
        views.index_teacher_teaching_achievement_select,name='index_teacher_teaching_achievement_select'),
    url(r'^index/teacher/teaching_achievement/delete/(?P<achievement_id>[0-9]+)/$',views.index_teacher_teaching_achievement_delete,name='index_teacher_teaching_achievement_delete'),
    url(r'^index/teacher/teaching_achievement/edit/(?P<achievement_id>[0-9]+)/$',views.index_teacher_teaching_achievement_edit, name='index_teacher_teaching_achievement_edit'),
    # teaching_object
    url(r'^index/teacher/teaching_object/$',views.index_teacher_teaching_object,name='index_teacher_teaching_object'),
    url(r'^index/teacher/teaching_object/select/$',views.index_teacher_teaching_object_select,name='index_teacher_teaching_object_select'),
    url(r'^index/teacher/teaching_object/add_new_object/$',
        views.index_teacher_new_teaching_object, name='index_teacheer_new_teaching_object'),
    url(r'^index/teacher/teaching_object/delete/(?P<object_id>[0-9]+)/$',
        views.index_teacher_teaching_object_delete,name='index_teacher_teaching_object_delete'),
    url(r'^index/teacher/teaching_object/edit/(?P<object_id>[0-9]+)/$',
        views.index_teacher_teaching_object_edit, name='index_teacher_teaching_object_edit'),

    # competition_guide
    url(r'^index/teacher/competition_guide/$',
        views.index_teacher_competition_guide, name='index_teacher_competition_guide'),
    url(r'^index/teacher/competition_guide/select/$',
        views.index_teacher_competition_guide_select,name='index_teacher_competition_guide_select'),
    url(r'^index/teacher/competition_guide/add/$',
        views.index_teacher_competition_guide_add, name='index_teacher_competition_guide_add'),
    url(r'^index/teacher/competition_guide/delete/(?P<competition_id>[0-9]+)/$',
        views.index_teacher_competition_guide_delete, name='index_teacher_competition_guide_delete'),
    url(r'^index/teacher/competition_guide/edit/(?P<competition_id>[0-9]+)/$',
        views.index_teacher_competition_guide_edit, name='index_teacher_competition_guide_edit'),
    # paper_guide
    url(r'^index/teacher/paper_guide/$',
        views.index_teacher_paper_guide, name='index_teacher_paper_guide'),
    url(r'^index/teacher/paper_guide/add/$',
        views.index_teacher_paper_guide_add, name='index_teacher_paper_guide_add'),
    url(r'^index/teacher/paper_guid/delete/(?P<paper_id>[0-9]+)/$',
        views.index_teacher_paper_guide_delete, name='index_teacher_paper_guide_delete'),
    url(r'^index/teacher/paper_guide/edit/(?P<paper_id>[0-9]+)/$',
        views.index_teacher_paper_guide_edit, name='index_teacher_paper_guide_edit'),
    url(r'^index/teacher/paper_guide/select/$',
        views.index_teacher_paper_guide_select, name='index_teacher_paper_guide_select'),
    # 教务员
    url(r'^index/academic_officer/$',
        views.index_academic_officer,name='index_academic_officer'),
    url(r'^index/academic_officer/set_year/$',
        views.index_A_O_set_year, name='index_A_O_set_year'),
    url(r'^index/academic_officer/set_input_date/(?P<number>[0-9]+)/$',
        views.index_A_O_input_time_set, name='index_A_O_input_time_set'),
    url(r'^index/academic_officer/set_page_item_total/$',
        views.index_A_O_set_page_item_total, name='index_A_O_set_page_item_total'),
    # url(r'^index/academic_officer/set_examination_date/(?P<number>[0-9]+)/$',
    #     views.index_A_O_examination_time_set, name='index_A_O_examination_time_set'),
    url(r'^index/academic_officer/workload_coefficent/$',
        views.index_AO_workload_coefficent, name='index_AO_workload_coefficent'),
    url(r'^index/workload_count/search/$', views.index_workload_count_search, name='index_workload_count_search'),
    url(r'^index/workload_count/select/$', views.index_workload_count_select, name='index_workload_count_select'),
    # 班级信息管理
    url(r'^index/academic_officer/basic_info/class_info/$',
        views.index_AO_class_info, name='index_AO_class_info'),
    url(r'^index/academic_officer/basic_info/class_info/add/$',
        views.index_AO_class_info_add, name='index_AO_class_info_add'),
    url(r'^index/academic_officer/basic_info/class_info/select/$',
        views.index_AO_class_info_select, name='index_AO_class_info_select'),
    url(r'^index/academic_officer/basic_info/class_info/edit/(?P<class_id>[0-9]+)/$',
        views.index_AO_class_info_edit, name='index_AO_class_info_edit'),
    url(r'^index/academic_officer/basic_info/class_info/select/(?P<class_id>[0-9]+)/$',
        views.index_AO_class_info_delete, name='index_AO_class_info_delete'),
    url(r'^index/acdemic_officer/basic_info/class_info/search/$',
        views.index_AO_class_info_search, name='index_AO_class_info_search'),
    # 课程信息管理
    url(r'^index/academic_officer/basic_info/course_info/$',
        views.index_AO_course_info, name='index_AO_course_info'),
    url(r'^index/academic_officer/basic_info/course_info/add/$',
        views.index_AO_course_info_add, name='index_AO_course_info_add'),
    url(r'^index/academic_officer/basic_info/course_info/select/$',
        views.index_AO_course_info_select, name='index_AO_course_info_select'),
    url(r'^index/academic_officer/basic_info/course_info/edit/(?P<course_id>[0-9]+)/$',
        views.index_AO_course_info_edit, name='index_AO_course_info_edit'),
    url(r'^index/academic_officer/basic_info/course_info/select/(?P<course_id>[0-9]+)/$',
        views.index_AO_course_info_delete, name='index_AO_course_info_delete'),
    url(r'^index/acdemic_officer/basic_info/course_info/search/$',
        views.index_AO_course_info_search, name='index_AO_course_info_search'),
    # 课程表信息管理
    url(r'^index/academic_officer/basic_info/class_schedul/teacher_list$',
        views.index_AO_teacher_list, name='index_AO_teacher_list'),
    url(r'^index/academic_officer/basic_info/class_schedul/course_listt$',
        views.index_AO_course_list, name='index_AO_course_list'),
    url(r'^index/academic_officer/basic_info/class_schedul/class_listt$',
        views.index_AO_class_list, name='index_AO_class_list'),
    url(r'^index/academic_officer/basic_info/class_schedul/$',
        views.index_AO_class_schedul, name='index_AO_class_schedul'),
    url(r'^index/academic_officer/basic_info/class_schedul/add/$',
        views.index_AO_class_schedul_add, name='index_AO_class_schedul_add'),
    url(r'^index/academic_officer/basic_info/class_schedul/select/$',
        views.index_AO_class_schedul_select, name='index_AO_class_schedul_select'),
    url(r'^index/academic_officer/basic_info/class_schedul/edit/(?P<class_schedul_id>[0-9]+)/$',
        views.index_AO_class_schedul_edit, name='index_AO_class_schedul_edit'),
    url(r'^index/academic_officer/basic_info/class_schedul/select/(?P<class_schedul_id>[0-9]+)/$',
        views.index_AO_class_schedul_delete, name='index_AO_class_schedul_delete'),
    url(r'^index/acdemic_officer/basic_info/class_schedul/search/$',
        views.index_AO_class_schedul_search, name='index_AO_class_schedul_search'),
    url(r'^index/acdemic_officer/basic_info/class_schedul/pass/$',
        views.index_AO_class_schedul_pass, name='index_AO_class_schedul_pass'),
    url(r'^index/acdemic_officer/basic_info/class_schedul/reject/$',
        views.index_AO_class_schedul_reject, name='index_AO_class_schedul_reject'),
    # 教学成果
    url(r'^index/academic_officer/teaching_achievement/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_achievement, name='index_A_O_SJ_teaching_achievement'),
    url(r'^index/academic_officer/teaching_achievement/search/$',
        views.index_A_O_SJ_teaching_achievement_search, name='index_A_O_SJ_teaching_achievement_search'),
    url(r'^index/academic_officer/teaching_achievement/select/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_achievement_select, name='index_A_O_SJ_teaching_achievement_select'),
    url(r'^index/academic_officer/teaching_achievement/pass/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_achievement_pass, name='A_O_SJ_teaching_achievement_pass'),
    url(r'^index/academic_officer/teaching_achievement/reject/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_achievement_reject, name='A_O_SJ_teaching_achievement_reject'),
    url(r'^index/academic_officer/teaching_achievement/reject/reason/$',
        views.index_A_O_teaching_achievement_reject_reason, name='index_A_O_teaching_achievement_reject_reason'),
    # 竞赛指导
    url(r'^index/academic_officer/competition_guide/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_competition_guide, name='index_A_O_SJ_competition_guide'),
    url(r'^index/academic_officer/competition_guide/search/$',
        views.index_A_O_SJ_competition_guide_search, name='index_A_O_SJ_competition_guide_search'),
    url(r'^index/academic_officer/competition_guide/select/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_competition_guide_select, name='index_A_O_SJ_competition_guide_select'),
    url(r'^index/academic_officer/competition_guide/pass/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_competition_guide_pass, name='index_A_O_SJ_competition_guide_pass'),
    url(r'^index/academic_officer/competition_guide/reject/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_competition_guide_reject, name='index_A_O_SJ_competition_guide_reject'),
    url(r'^index/academic_officer/competition/reject/reason/$',
        views.index_A_O_competition_guide_reject_reason, name='index_A_O_competition_guide_reject_reason'),
    # 教学项目
    url(r'^index/academic_officer/teaching_object/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_object, name='index_A_O_SJ_teaching_object'),
    url(r'^index/academic_officer/teaching_object/search/$',
        views.index_A_O_SJ_teaching_object_search, name='index_A_O_SJ_teaching_object_search'),
    url(r'^index/academic_officer/teaching_object/select/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_object_select, name='index_A_O_SJ_teaching_object_select'),
    url(r'^index/academic_officer/teaching_object/pass/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_object_pass, name='index_A_O_SJ_teaching_object_pass'),
    url(r'^index/academic_officer/teaching_object/reject/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_teaching_object_reject, name='index_A_O_SJ_teaching_object_reject'),
    url(r'^index/academic_officer/teaching_object/reject/reason/$',
        views.index_A_O_teaching_object_reject_reason, name='index_A_O_teaching_object_reject_reason'),


    # 论文指导
    url(r'^index/academic_officer/paper_guide/search/$',
        views.index_A_O_SJ_paper_guide_search, name='index_A_O_SJ_paper_guide_search'),
    url(r'^index/academic_officer/paper_guide/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_paper_guide, name='index_A_O_SJ_paper_guide'),
    url(r'^index/academic_officer/paper_guide/select/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_paper_guide_select, name='index_A_O_SJ_paper_guide_select'),
    url(r'^index/academic_officer/paper_guide/pass/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_paper_guide_pass, name='index_A_O_SJ_paper_guide_pass'),
    url(r'^index/academic_officer/paper_guide/reject/(?P<department_id>[0-9]+)/$',
        views.index_A_O_SJ_paper_guide_reject, name='index_A_O_SJ_paper_guide_reject'),
    url(r'^index/academic_officer/paper/reject/reason/$',
        views.index_A_O_papaer_guide_reject_reason, name='index_A_O_papaer_guide_reject_reason'),

    # 系负责人
    # 生信

    url(r'^index/bioinfomation/$',
        views.index_D_H_bioinfomation, name='index_D_H_bioinfomation'),
    # 生工
    url(r'^index/bioobject/$',
        views.index_D_H_bioobject, name='index_D_H_bioobject'),
    # 生技
    url(r'^index/department_header/management_of_teacher_source/edit/(?P<teacher_id>[0-9]+)/$',
        views.MOTRS_teacher_info_edit, name='MOTRS_teacher_info_edit'),
    url(r'^index/department_header/management_of_teacher_source/delete/(?P<teacher_id>[0-9]+)/$',
        views.MOTRS_teacher_info_delete, name='MOTRS_teacher_info_delete'),
    url(r'^index/biotechnology/$',
        views.index_D_H_biotechnology, name='index_D_H_biotechnology'),
    # 教师信息管理
    url(r'^index/department_header/management_of_teacher_resource/(?P<department_id>[0-9])/$',
            views.management_of_teacher_resource, name='management_of_teacher_resource'),
    url(r'^index/department_header/management_of_teacher_resource/select/$',
                views.management_of_teacher_resource_select, name='management_of_teacher_resource_select'),
    url(r'^index/department_header/management_of_teacher_resource/search/(?P<department_id>[0-9])/$',
            views.management_of_teacher_resource_search, name='management_of_teacher_resource_search'),
    url(r'^index/excel/$',
        views.some_streaming_csv_view, name='some_streaming_csv_view'),
    # 导出excel
    url(r'^index/excel/download/workload/chose/$',
        views.excel_chose_view, name='excel_chose_view'),
    url(r'^index/excel/download/(?P<download_type>[0-9])/$',
        views.some_excel_ret_view, name='some_excel_ret_view'),
    url(r'^index/excel/download/teacher_info/$',
        views.excel_teacher_ret_view, name='excel_teacher_ret_view'),
    url(r'^index/excel/download/class_info/$',
        views.excel_class_ret_view, name='excel_class_ret_view'),
    url(r'^index/excel/download/course_info/$',
        views.excel_course_ret_view, name='excel_course_ret_view'),
    url(r'^index/excel/download/class_schedul/$',
        views.excel_class_schedule_ret_view, name='excel_class_schedule_ret_view'),
    # 导入excel
    url(r'^index/excel/upload/teacher/$',
        views.excel_upload_teacher, name='excel_upload_teacher'),
    url(r'^index/excel/upload/class/$',
        views.excel_upload_class, name='excel_upload_class'),
    url(r'^index/excel/upload/course/$',
        views.excel_upload_course, name='excel_upload_course'),
    url(r'^index/excel/upload/class_schedul/$',
        views.excel_upload_class_schedul, name='excel_upload_class_schedul'),


    # url(r'^index/sendemail/$',
    #         views.send_mail, name='send_mail'),
]